/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/zhangliping/Desktop/codeup/shaelynblog.github.io/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-d8780b00",
    path: "/bug/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d8780b00").then(next)
    },
  },
  {
    path: "/bug/index.html",
    redirect: "/bug/"
  },
  {
    name: "v-ae39ac52",
    path: "/bug/tool.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ae39ac52").then(next)
    },
  },
  {
    name: "v-df7af9de",
    path: "/essays/sentence.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df7af9de").then(next)
    },
  },
  {
    name: "v-d7dfa85e",
    path: "/essays/toolbook.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7dfa85e").then(next)
    },
  },
  {
    name: "v-16a79cde",
    path: "/fun/htmlcss.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16a79cde").then(next)
    },
  },
  {
    name: "v-39b1cefa",
    path: "/talk/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39b1cefa").then(next)
    },
  },
  {
    path: "/talk/index.html",
    redirect: "/talk/"
  },
  {
    name: "v-a7e76322",
    path: "/talk/outsourcers.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7e76322").then(next)
    },
  },
  {
    name: "v-fe35296c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe35296c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-3235da42",
    path: "/basics/frond.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3235da42").then(next)
    },
  },
  {
    name: "v-026b98d1",
    path: "/essays/book.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-026b98d1").then(next)
    },
  },
  {
    name: "v-7653377b",
    path: "/basics/websecure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7653377b").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]