/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\code\\shaelynblog.github.io\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-371a8c24",
    path: "/bug/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-371a8c24").then(next)
    },
  },
  {
    path: "/bug/index.html",
    redirect: "/bug/"
  },
  {
    name: "v-3a110e4b",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a110e4b").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-1a9390ab",
    path: "/basics/frond.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a9390ab").then(next)
    },
  },
  {
    name: "v-3c34ea86",
    path: "/bug/%E8%B7%A8%E5%9F%9F%E8%AF%B7%E6%B1%82%E6%96%B9%E5%BC%8F%E5%8F%98%E4%B8%BAOPTIONS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c34ea86").then(next)
    },
  },
  {
    path: "/bug/跨域请求方式变为OPTIONS.html",
    redirect: "/bug/%E8%B7%A8%E5%9F%9F%E8%AF%B7%E6%B1%82%E6%96%B9%E5%BC%8F%E5%8F%98%E4%B8%BAOPTIONS.html"
  },
  {
    path: "/bug/跨域请求方式变为OPTIONS.html",
    redirect: "/bug/%E8%B7%A8%E5%9F%9F%E8%AF%B7%E6%B1%82%E6%96%B9%E5%BC%8F%E5%8F%98%E4%B8%BAOPTIONS.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]