/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "老张の部落格",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "错题本",
      "frontmatter": {},
      "regularPath": "/bug/",
      "relativePath": "bug/README.md",
      "key": "v-371a8c24",
      "path": "/bug/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/cat.jpg",
        "actionText": "走着 →",
        "actionLink": "/basics/frond.html"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3a110e4b",
      "path": "/"
    },
    {
      "title": "JavaScript 面向对象",
      "frontmatter": {},
      "regularPath": "/basics/frond.html",
      "relativePath": "basics/frond.md",
      "key": "v-1a9390ab",
      "path": "/basics/frond.html",
      "headers": [
        {
          "level": 2,
          "title": "原型",
          "slug": "原型"
        },
        {
          "level": 2,
          "title": "原型链",
          "slug": "原型链"
        },
        {
          "level": 2,
          "title": "基于 prototype 的继承",
          "slug": "基于-prototype-的继承"
        },
        {
          "level": 2,
          "title": "es6 面向对象",
          "slug": "es6-面向对象"
        }
      ]
    },
    {
      "title": "跨域请求方式变为 OPTIONS",
      "frontmatter": {},
      "regularPath": "/bug/%E8%B7%A8%E5%9F%9F%E8%AF%B7%E6%B1%82%E6%96%B9%E5%BC%8F%E5%8F%98%E4%B8%BAOPTIONS.html",
      "relativePath": "bug/跨域请求方式变为OPTIONS.md",
      "key": "v-3c34ea86",
      "path": "/bug/%E8%B7%A8%E5%9F%9F%E8%AF%B7%E6%B1%82%E6%96%B9%E5%BC%8F%E5%8F%98%E4%B8%BAOPTIONS.html"
    }
  ],
  "themeConfig": {
    "search": true,
    "nav": [
      {
        "text": "基本功",
        "link": "/basics/frond.html"
      },
      {
        "text": "错题本",
        "link": "/bug/跨域请求方式变为OPTIONS.html"
      }
    ],
    "sidebar": [
      "/basics/frond.html",
      "/bug/"
    ]
  }
}