/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "老张の部落格",
  "description": "Good good study ,day day up",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/logo.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/cat.jpg",
        "actionText": "走着 →",
        "actionLink": "/basics/frond.html"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3a110e4b",
      "path": "/"
    },
    {
      "title": "浅谈web安全",
      "frontmatter": {},
      "regularPath": "/basics/websecure.html",
      "relativePath": "basics/websecure.md",
      "key": "v-a685ad72",
      "path": "/basics/websecure.html",
      "headers": [
        {
          "level": 2,
          "title": "常见的web安全问题",
          "slug": "常见的web安全问题"
        },
        {
          "level": 3,
          "title": "越权",
          "slug": "越权"
        },
        {
          "level": 3,
          "title": "跨域漏洞",
          "slug": "跨域漏洞"
        },
        {
          "level": 3,
          "title": "注入风险",
          "slug": "注入风险"
        },
        {
          "level": 3,
          "title": "xss跨站脚本攻击",
          "slug": "xss跨站脚本攻击"
        },
        {
          "level": 3,
          "title": "csrf跨站请求伪造",
          "slug": "csrf跨站请求伪造"
        },
        {
          "level": 2,
          "title": "前端安全",
          "slug": "前端安全"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "前端",
      "frontmatter": {},
      "regularPath": "/basics/frond.html",
      "relativePath": "basics/frond.md",
      "key": "v-1a9390ab",
      "path": "/basics/frond.html",
      "headers": [
        {
          "level": 2,
          "title": "前端模块化之 CommonJS 与 ES6 模块化",
          "slug": "前端模块化之-commonjs-与-es6-模块化"
        },
        {
          "level": 3,
          "title": "为什么要使用前端模块化",
          "slug": "为什么要使用前端模块化"
        },
        {
          "level": 3,
          "title": "什么是前端模块化",
          "slug": "什么是前端模块化"
        },
        {
          "level": 3,
          "title": "ES6 模块化",
          "slug": "es6-模块化"
        },
        {
          "level": 3,
          "title": "ES6 模块化的几种导出方式:",
          "slug": "es6-模块化的几种导出方式"
        },
        {
          "level": 3,
          "title": "CommonJS",
          "slug": "commonjs"
        },
        {
          "level": 3,
          "title": "babel",
          "slug": "babel"
        },
        {
          "level": 2,
          "title": "JavaScript 面向对象",
          "slug": "javascript-面向对象"
        },
        {
          "level": 3,
          "title": "原型",
          "slug": "原型"
        },
        {
          "level": 3,
          "title": "原型链",
          "slug": "原型链"
        },
        {
          "level": 3,
          "title": "基于 prototype 的继承",
          "slug": "基于-prototype-的继承"
        },
        {
          "level": 3,
          "title": "es6 面向对象",
          "slug": "es6-面向对象"
        },
        {
          "level": 2,
          "title": "js类型判断",
          "slug": "js类型判断"
        },
        {
          "level": 3,
          "title": "typeof",
          "slug": "typeof"
        },
        {
          "level": 3,
          "title": "instanceof",
          "slug": "instanceof"
        },
        {
          "level": 3,
          "title": "Object.prototype.toString.call",
          "slug": "object-prototype-tostring-call"
        },
        {
          "level": 2,
          "title": "跨域解决方案",
          "slug": "跨域解决方案"
        },
        {
          "level": 3,
          "title": "跨域",
          "slug": "跨域"
        },
        {
          "level": 3,
          "title": "服务端设置cors头",
          "slug": "服务端设置cors头"
        },
        {
          "level": 3,
          "title": "webpack中提供devserver",
          "slug": "webpack中提供devserver"
        },
        {
          "level": 3,
          "title": "node-http-proxy 模块",
          "slug": "node-http-proxy-模块"
        },
        {
          "level": 3,
          "title": "使用nginx代理转发",
          "slug": "使用nginx代理转发"
        },
        {
          "level": 3,
          "title": "JSONP",
          "slug": "jsonp"
        }
      ]
    },
    {
      "title": "HTTP",
      "frontmatter": {},
      "regularPath": "/bug/",
      "relativePath": "bug/README.md",
      "key": "v-371a8c24",
      "path": "/bug/",
      "headers": [
        {
          "level": 2,
          "title": "跨域请求方式变为 OPTIONS",
          "slug": "跨域请求方式变为-options"
        }
      ]
    },
    {
      "title": "课外书",
      "frontmatter": {},
      "regularPath": "/essays/book.html",
      "relativePath": "essays/book.md",
      "key": "v-2af7199d",
      "path": "/essays/book.html",
      "headers": [
        {
          "level": 2,
          "title": "《把自己当回事儿》杨天真",
          "slug": "《把自己当回事儿》杨天真"
        },
        {
          "level": 3,
          "title": "简介",
          "slug": "简介"
        },
        {
          "level": 3,
          "title": "摘抄",
          "slug": "摘抄"
        },
        {
          "level": 3,
          "title": "普鲁斯特问卷",
          "slug": "普鲁斯特问卷"
        }
      ]
    },
    {
      "title": "那些年踩的坑——工具类",
      "frontmatter": {},
      "regularPath": "/bug/tool.html",
      "relativePath": "bug/tool.md",
      "key": "v-7bb0d2a9",
      "path": "/bug/tool.html",
      "headers": [
        {
          "level": 2,
          "title": "Error: Could not find any Visual Studio installation to use",
          "slug": "error-could-not-find-any-visual-studio-installation-to-use"
        },
        {
          "level": 3,
          "title": "情景再现",
          "slug": "情景再现"
        },
        {
          "level": 3,
          "title": "解决方案",
          "slug": "解决方案"
        },
        {
          "level": 3,
          "title": "具体操作",
          "slug": "具体操作"
        },
        {
          "level": 3,
          "title": "Tips",
          "slug": "tips"
        },
        {
          "level": 2,
          "title": "nodemon热更新显示端口占用",
          "slug": "nodemon热更新显示端口占用"
        },
        {
          "level": 3,
          "title": "解决方式",
          "slug": "解决方式"
        },
        {
          "level": 2,
          "title": "vscode 远程同步插件SFTP使用指引",
          "slug": "vscode-远程同步插件sftp使用指引"
        },
        {
          "level": 3,
          "title": "vscode 向远程云开发机同步代码",
          "slug": "vscode-向远程云开发机同步代码"
        }
      ]
    },
    {
      "title": "小句子",
      "frontmatter": {},
      "regularPath": "/essays/sentence.html",
      "relativePath": "essays/sentence.md",
      "key": "v-5bd677dd",
      "path": "/essays/sentence.html"
    },
    {
      "title": "实用/工具类",
      "frontmatter": {},
      "regularPath": "/essays/toolbook.html",
      "relativePath": "essays/toolbook.md",
      "key": "v-5fa4209d",
      "path": "/essays/toolbook.html",
      "headers": [
        {
          "level": 2,
          "title": "《网络是怎样连接的》[日]户根勤",
          "slug": "《网络是怎样连接的》-日-户根勤"
        },
        {
          "level": 3,
          "title": "网络的全貌",
          "slug": "网络的全貌"
        },
        {
          "level": 2,
          "title": "《起床后的黄金1小时》[日]池田千惠",
          "slug": "《起床后的黄金1小时》-日-池田千惠"
        },
        {
          "level": 3,
          "title": "章节概要",
          "slug": "章节概要"
        },
        {
          "level": 3,
          "title": "利用早起，提高工作效率",
          "slug": "利用早起-提高工作效率"
        },
        {
          "level": 3,
          "title": "早起，遇见全新的自己",
          "slug": "早起-遇见全新的自己"
        },
        {
          "level": 3,
          "title": "做”神奇“的事，成为出众的人",
          "slug": "做-神奇-的事-成为出众的人"
        },
        {
          "level": 3,
          "title": "制定你的早起方案",
          "slug": "制定你的早起方案"
        },
        {
          "level": 3,
          "title": "只要起床，就是一场胜利",
          "slug": "只要起床-就是一场胜利"
        }
      ]
    },
    {
      "title": "html/css",
      "frontmatter": {},
      "regularPath": "/fun/htmlcss.html",
      "relativePath": "fun/htmlcss.md",
      "key": "v-357874e3",
      "path": "/fun/htmlcss.html",
      "headers": [
        {
          "level": 2,
          "title": "利用html热区技术监听图片点击事件",
          "slug": "利用html热区技术监听图片点击事件"
        },
        {
          "level": 3,
          "title": "如何设置html热区？",
          "slug": "如何设置html热区"
        },
        {
          "level": 3,
          "title": "map",
          "slug": "map"
        },
        {
          "level": 3,
          "title": "area",
          "slug": "area"
        },
        {
          "level": 2,
          "title": "搜索过滤和滚动定位",
          "slug": "搜索过滤和滚动定位"
        },
        {
          "level": 3,
          "title": "实现",
          "slug": "实现"
        },
        {
          "level": 3,
          "title": "滚动定位",
          "slug": "滚动定位"
        },
        {
          "level": 3,
          "title": "字体闪烁",
          "slug": "字体闪烁"
        },
        {
          "level": 3,
          "title": "搜索过滤",
          "slug": "搜索过滤"
        },
        {
          "level": 3,
          "title": "注意",
          "slug": "注意"
        },
        {
          "level": 2,
          "title": "关于iframe",
          "slug": "关于iframe"
        },
        {
          "level": 3,
          "title": "关于iframe的HTML标准",
          "slug": "关于iframe的html标准"
        },
        {
          "level": 3,
          "title": "如何使用iframe展示局部页面内容?",
          "slug": "如何使用iframe展示局部页面内容"
        },
        {
          "level": 3,
          "title": "跨域的iframe获取iframe内的dom元素",
          "slug": "跨域的iframe获取iframe内的dom元素"
        },
        {
          "level": 3,
          "title": "ElementUI el-table的fixed固定列引发的bug",
          "slug": "elementui-el-table的fixed固定列引发的bug"
        }
      ]
    },
    {
      "title": "嘴碎",
      "frontmatter": {},
      "regularPath": "/talk/",
      "relativePath": "talk/README.md",
      "key": "v-db133624",
      "path": "/talk/"
    },
    {
      "title": "关于外包",
      "frontmatter": {},
      "regularPath": "/talk/outsourcers.html",
      "relativePath": "talk/outsourcers.md",
      "key": "v-42dcb8fb",
      "path": "/talk/outsourcers.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是外包",
          "slug": "什么是外包"
        },
        {
          "level": 3,
          "title": "外包模式",
          "slug": "外包模式"
        },
        {
          "level": 3,
          "title": "大多数人眼中的外包",
          "slug": "大多数人眼中的外包"
        },
        {
          "level": 2,
          "title": "我的外包经历",
          "slug": "我的外包经历"
        },
        {
          "level": 3,
          "title": "我的第一份工作",
          "slug": "我的第一份工作"
        },
        {
          "level": 3,
          "title": "原来和很优秀的人共事是这种感觉",
          "slug": "原来和很优秀的人共事是这种感觉"
        },
        {
          "level": 2,
          "title": "千万不要去外包？？",
          "slug": "千万不要去外包"
        },
        {
          "level": 3,
          "title": "正式员工眼中的外包",
          "slug": "正式员工眼中的外包"
        },
        {
          "level": 3,
          "title": "心态",
          "slug": "心态"
        },
        {
          "level": 2,
          "title": "致谢",
          "slug": "致谢"
        }
      ]
    }
  ],
  "themeConfig": {
    "search": true,
    "displayAllHeaders": true,
    "nav": [
      {
        "text": "基本功",
        "link": "/basics/frond.html"
      },
      {
        "text": "错题本",
        "link": "/bug/"
      },
      {
        "text": "有趣的功能",
        "link": "/fun/htmlcss.html"
      },
      {
        "text": "碎碎念",
        "link": "/talk/"
      },
      {
        "text": "随笔",
        "items": [
          {
            "text": "读书笔记",
            "items": [
              {
                "text": "实用类",
                "link": "/essays/toolbook.html"
              },
              {
                "text": "课外书",
                "link": "/essays/book.html"
              }
            ]
          },
          {
            "text": "小句子",
            "link": "/essays/sentence.html"
          }
        ]
      }
    ],
    "sidebar": {
      "/basics/": [
        {
          "title": "基本功",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            "frond",
            "websecure"
          ]
        }
      ],
      "/bug/": [
        {
          "title": "错题本",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            "",
            "tool"
          ]
        }
      ],
      "/fun/": [
        {
          "title": "有趣的功能",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            "htmlcss"
          ]
        }
      ],
      "/talk/": [
        {
          "title": "碎碎念",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            "",
            "outsourcers"
          ]
        }
      ],
      "/essays/": [
        {
          "title": "随笔",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            "toolbook",
            "book",
            "sentence"
          ]
        }
      ]
    }
  }
}